from typing import Any

class StrAndRepr: ...

def evaluate_string(string: Any) -> Any: ...

class Token(StrAndRepr):
    type: Any = ...
    def __init__(self, type: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
